#!/usr/bin/python3

#----------------------------------------------
# MODULES
#----------------------------------------------
from treeBindings_VHDLgen import wrFA, wrHA, vhdlDaddaLevel

#----------------------------------------------
# VARIABLES
#----------------------------------------------
fileName = "./autoGeneratedDaddaTree.vhd"
daddaLevels = 5
daddaRows = [2, 3, 4, 6, 9, 13]

numElmArr = []
faArr = []
haArr = []

#----------------------------------------------
# PROGRAM
#----------------------------------------------
srcMtx = "grid5"
dstMtx = "grid4"
srcMtxRows = 13
dstMtxRows = daddaRows[daddaLevels-1]
mtxCols = 46

for i in range(2, 14):
	numElmArr += [i]
	numElmArr += [i-1]
numElmArr += [12] * 3
numElmArr += [11]
for i in range(0, 9):
	numElmArr += [10-i] * 2

faArr += [0] * 18
faArr += [1] * 2
faArr += [2] * 2
faArr += [3] * 6
faArr += [2]
faArr += [1] * 2
faArr += [0] * 15

haArr += [0] * 16 
haArr += [1] * 11
haArr += [0] * 2
haArr += [1]
haArr += [0]
haArr += [1]
haArr += [0] * 14

vhdlDaddaLevel(fileName, "w", srcMtx, dstMtx, srcMtxRows, dstMtxRows, mtxCols, numElmArr, faArr, haArr, 4)
numElmArr.clear()
faArr.clear()
haArr.clear()


srcMtx = "grid4"
dstMtx = "grid3"
srcMtxRows = daddaRows[daddaLevels-1]
dstMtxRows = daddaRows[daddaLevels-2]
mtxCols = 46

for i in range(2, 10):
	numElmArr += [i]
	numElmArr += [i-1]
numElmArr += [9] * 17
numElmArr += [8]
for i in range(0, 6):
	numElmArr += [7-i] * 2

faArr += [0] * 12
faArr += [1] * 2
faArr += [2] * 2
faArr += [3] * 17
faArr += [2] * 2
faArr += [1] * 2
faArr += [0] * 9

haArr += [0] * 10
haArr += [1] * 6
haArr += [0] * 17
haArr += [1] 
haArr += [0]
haArr += [1]
haArr += [0]
haArr += [1]
haArr += [0] * 8

vhdlDaddaLevel(fileName, "a", srcMtx, dstMtx, srcMtxRows, dstMtxRows, mtxCols, numElmArr, faArr, haArr, 3)
numElmArr.clear()
faArr.clear()
haArr.clear()


srcMtx = "grid3"
dstMtx = "grid2"
srcMtxRows = daddaRows[daddaLevels-2]
dstMtxRows = daddaRows[daddaLevels-3]
mtxCols = 46

for i in range(2, 7):
	numElmArr += [i]
	numElmArr += [i-1]
numElmArr += [6] * 29
numElmArr += [5]
for i in range(2, 5):
	numElmArr += [6-i] * 2 

faArr += [0] * 8
faArr += [1] * 2
faArr += [2] * 29
faArr += [1] * 2
faArr += [0] * 5 

haArr += [0] * 6
haArr += [1] * 4
haArr += [0] * 29
haArr += [1]
haArr += [0]
haArr += [1]
haArr += [0] * 4

vhdlDaddaLevel(fileName, "a", srcMtx, dstMtx, srcMtxRows, dstMtxRows, mtxCols, numElmArr, faArr, haArr, 2)
numElmArr.clear()
faArr.clear()
haArr.clear()


srcMtx = "grid2"
dstMtx = "grid1"
srcMtxRows = daddaRows[daddaLevels-3]
dstMtxRows = daddaRows[daddaLevels-4]
mtxCols = 46 

numElmArr += [2]
numElmArr += [1]
numElmArr += [3]
numElmArr += [2]
numElmArr += [4]
numElmArr += [3]
numElmArr += [4] * 37
numElmArr += [3]
numElmArr += [2] * 2

faArr += [0] * 6
faArr += [1] * 37
faArr += [0] * 3

haArr += [0] * 4
haArr += [1] * 2
haArr += [0] * 37
haArr += [1]
haArr += [0] * 2

vhdlDaddaLevel(fileName, "a", srcMtx, dstMtx, srcMtxRows, dstMtxRows, mtxCols, numElmArr, faArr, haArr, 1)
numElmArr.clear()
faArr.clear()
haArr.clear()


srcMtx = "grid1"
dstMtx = "grid0"
srcMtxRows = daddaRows[daddaLevels-4]
dstMtxRows = daddaRows[daddaLevels-5]
mtxCols = 46

numElmArr += [2]
numElmArr += [1]
numElmArr += [3]
numElmArr += [2]
numElmArr += [3] * 41
numElmArr += [2]

faArr += [0] * 4
faArr += [1] * 41
faArr += [0]

haArr += [0] * 2
haArr += [1] * 2
haArr += [0] * 41
haArr += [1]

vhdlDaddaLevel(fileName, "a", srcMtx, dstMtx, srcMtxRows, dstMtxRows, mtxCols, numElmArr, faArr, haArr, 0)
numElmArr.clear()
faArr.clear()
haArr.clear()
