arith_path='/home/clmcasino/Desktop/ISA/Lab2/ISA-digital-arithmetic/HW_filter/version2/script/py_model'

input_sample_fname='multSample.txt'

sw_mult_result_fpath=       'result/C0DleftA0_mbeDadda_mult_wRegs_mult_SW-output.txt'
sw_filter_result_fpath=     'result/filter_SW-output.txt'
sw_filter_result_fpath2s=   'result/filter_SW-2soutput.txt'

res_trunc_mult_path=        'result'
res_trunc_mult_ID=          'mbeDadda_mult_wRegs_mult_HW-output'
res_trunc_filter_path=      'result'
res_trunc_filter_ID=        'iir_filter_filter_HW-output'
rep_trunc_mult_path=        'report'
rep_trunc_mult_ID=          'mbeDadda_mult_wRegs'
rep_trunc_filter_path=      'report'
rep_trunc_filter_ID=        'iir_filter'
res_approxCompr_mult_path=  'result'
res_approxCompr_mult_ID=    'mbeDadda_mult_wRegs_mult_HW-output'
res_approxCompr_filter_path='result'
res_approxCompr_filter_ID=  'iir_filter_filter_HW-output'
rep_approxCompr_mult_path=  'report'
rep_approxCompr_mult_ID=    'mbeDadda_mult_wRegs'
rep_approxCompr_filter_path='report'
rep_approxCompr_filter_ID=  'iir_filter'

logRel_stat_trunc_mult_fpath=       'log/Trunc_mbeDadda_mult_wRegs_mult_RelAnalysisLog.txt'
logRel_stat_trunc_filter_fpath=     'log/Trunc_iir_filter_RelAnalysisLog.txt'
logAbs_stat_trunc_mult_fpath=       'log/Trunc_mbeDadda_mult_wRegs_mult_AbsAnalysisLog.txt'
logAbs_stat_trunc_filter_fpath=     'log/Trunc_iir_filter_AbsAnalysisLog.txt'
log_rep_trunc_mult_fpath=           'log/Trunc_mbeDadda_mult_wRegs_mult_ReportLog'
log_rep_trunc_filter_fpath=         'log/Trunc_iir_filter_filter_ReportLog.txt'
logRel_stat_approxCompr_mult_fpath= 'log/ApproxCompr_mbeDadda_mult_wRegs_mult_RelAnalysisLog.txt'
logRel_stat_approxCompr_filter_fpath='log/ApproxCompr_iir_filter_RelAnalysisLog.txt'
logAbs_stat_approxCompr_mult_fpath= 'log/ApproxCompr_mbeDadda_mult_wRegs_mult_AbsAnalysisLog.txt'
logAbs_stat_approxCompr_filter_fpath='log/ApproxCompr_iir_filter_AbsAnalysisLog.txt'
log_rep_approxCompr_mult_fpath=     'log/ApproxCompr_mbeDadda_mult_wRegs_mult_ReportLog'
log_rep_approxCompr_filter_fpath=   'log/ApproxCompr_iir_filter_filter_ReportLog.txt'

matlab_trunc_values=                'matlab/Trunc_Values.txt'
matlab_trunc_mult_statMax=          'matlab/Trunc_mult_StatMax.txt'
matlab_trunc_filter_statMax=        'matlab/Trunc_filter_StatMax.txt'
matlab_trunc_mult_statAvg=          'matlab/Trunc_mult_StatAvg.txt'
matlab_trunc_filter_statAvg=        'matlab/Trunc_filter_StatAvg.txt'
matlab_trunc_mult_areas=            'matlab/Trunc_mult_Areas.txt'
matlab_trunc_mult_timing=           'matlab/Trunc_mult_Timing.txt'
matlab_trunc_filter_areas=          'matlab/Trunc_filter_Areas.txt'
matlab_trunc_filter_timing=         'matlab/Trunc_filter_Timing.txt'
matlab_approxCompr_values=          'matlab/ApproxCompr_Values.txt'
matlab_approxCompr_mult_statMax=    'matlab/ApproxCompr_mult_StatMax.txt'
matlab_approxCompr_filter_statMax=  'matlab/ApproxCompr_filter_StatMax.txt'
matlab_approxCompr_mult_statAvg=    'matlab/ApproxCompr_mult_StatAvg.txt'
matlab_approxCompr_filter_statAvg=  'matlab/ApproxCompr_filter_StatAvg.txt'
matlab_approxCompr_mult_areas=      'matlab/ApproxCompr_mult_Areas.txt'
matlab_approxCompr_mult_timing=     'matlab/ApproxCompr_mult_Timing.txt'
matlab_approxCompr_filter_areas=    'matlab/ApproxCompr_filter_Areas.txt'
matlab_approxCompr_filter_timing=   'matlab/ApproxCompr_filter_Timing.txt'

sw_res_fname="SW_result.txt"
max_out_par=46
mult_out_par=24
filter_out_par=13
numSamples=250000
